### ISSUE TITLE
Finding project partners based on your interests

### ISSUE THREAD

**Issue by rupeshmohanty** [Spectrum-CETB/LesKollab#3]
When an user clicks on the 'Find a Project Partner' then he/she will Register and based on their interests can find projects they can contribute to. The feature should be linked to this button:
![image](https://user-images.githubusercontent.com/43889891/107856757-65d79b80-6e50-11eb-868d-28577b5ca87a.png)

**Comment by bhavyashukla16** [comment]
can you please assign this issue to me?

**Comment by Goheljay** [comment]
I am interested to work on this issue. can I work it?

**Comment by subhangi2731** [comment]
can I work on this?

**Comment by Siddharth1006** [comment]
@rupeshmohanty I am a GSSOC'21 participant and would love to work on this project. 

I had a question:
It is mentioned that when we click the button, we should display a list of projects according to our interests. So, that means we should already have a repository of projects and links to those projects ready with us , so that for a keyword = "Javascript", all javascript based projects should be displayed.
So, should we scour the internet from our side and find projects for some techstack?

this is my understanding. If I am wrong, please correct me. 

If its correct, I would love to start working on it.

**Comment by feni-katharotiya** [comment]
@rupeshmohanty . Hello, I am gssoc participant and would like to work on this issue.

**Comment by feni-katharotiya** [comment]
@rupeshmohanty  Hello, I am gssoc participant and would like to work on this issue.

**Comment by Nikitha2309** [comment]
### Proposal

I am a GSSoC'21 participant and I want to work on this issue. Please assign this issue to me.

### Protocol

To fix this issue, a basic form ( similar to that in index.php of this project ) is to be implemented and required fields are collected as inputs. The button "Find a Project Partner" will link to this pop-up modal form or page.

Looking forward to getting this Issue assigned to me and work on it, Thank you

**Comment by rupeshmohanty** [comment]
Hey guys, This issue has been assigned to one contributor for the time being, so try to solve other issues or try to create your own issues and contribute. 

And while contributing please use the issue template provided.
